In [1]:
import numpy as np
import pandas as pd
np.random.seed(42)

In [2]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

# Matrices y vectores en Numpy

#### En Numpy, el tipo de datos principal es el ndarray (N-dimensional array)

## Creación de ndarrays

In [67]:
# PODEMOS CREAR NRDARRYS...
# Usando la función array
data = np.array([3, 4, 5, 6, 7, 8])
data #--> 1d array
more_data = np.array([[3, 5, 6], [7, 8, 9]])
more_data #--> 2d array
even_more_data = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
even_more_data # --> 3d array

array([3, 4, 5, 6, 7, 8])

array([[3, 5, 6],
       [7, 8, 9]])

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [10]:
# Generando un ndarray específico con las funciones zeros, ones, empty y fill
ones = np.ones(4)
ones
zeros = np.zeros((4, 5)) # (x,y) indica la forma (shape) de nuestro array
zeros
empty_values = np.empty((3, 3)) # Sólo reserva espacio en memoria. ¡Cuidado con la basura!
empty_values
fives = np.full((4, 3), 5)
fives

array([1., 1., 1., 1.])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

array([[0.   , 0.125, 0.25 ],
       [0.375, 0.5  , 0.625],
       [0.75 , 0.875, 1.   ]])

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [68]:
# Usando funciones del módulo random
random = np.random.randn(2, 2)
random
random_ints = np.random.randint(5, 10, (2, 2))
random_ints

array([[ 1.38590332,  1.00860295],
       [-1.63221808,  0.28096432]])

array([[9, 8],
       [7, 6]])

In [72]:
# Usando la función arange
ints = np.arange(15)
ints

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Casting de arrays

In [85]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)

arr1.dtype
arr3 = arr1.astype(np.float64)
arr3
arr3.dtype

dtype('float64')

array([1., 2., 3.])

dtype('float64')

## Propiedades de los arrays

In [76]:
# PRESENTAN TIPO DE DATO, FORMA, DIMENSIONES
data.dtype
random.dtype

ones.shape
fives.shape
even_more_data.shape

zeros.ndim
even_more_data.shape

dtype('int64')

dtype('float64')

(4,)

(4, 3)

(2, 2, 2)

2

(2, 2, 2)

## Aritmética de ndarrays

In [95]:
# EL USO DE OPERADORES (+,-,*,/) OBEDECE CIERTAS REGLAS
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

dtype('float64')

In [96]:
# Producto
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [97]:
# Suma
arr + arr

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])

In [98]:
# Producto escalar
arr * 2

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])

In [99]:
# Operaciones condicionales
arr > 3
arr != 1

array([[False, False, False],
       [ True,  True,  True]])

array([[False,  True,  True],
       [ True,  True,  True]])

## Indexing

In [109]:
# PODEMOS ACCEDER A VALORES ESPECÍFICOS DE UN ARRAY
arr1 = np.arange(10)
arr2 = np.arange(9).reshape((3, 3))
arr3 = np.arange(8).reshape((2, 2, 2))
arr1
arr2
arr3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

### Básico

In [110]:
arr1[5]
arr1[-1]
arr1[-2]

5

9

8

In [114]:
arr2[2]
arr2[-1]

array([6, 7, 8])

array([6, 7, 8])

In [118]:
arr3[0]
arr3[-1]

array([[0, 1],
       [2, 3]])

array([[4, 5],
       [6, 7]])

In [ ]:
# Selección mas granular

In [120]:
arr2[1, 2]
arr2[1][2]

5

5

In [124]:
arr3[1, 1, 1]
arr3[1][1][1]

7

7

In [106]:
# Asignación a valores indexados
arr1[0] = 100
arr1
arr1[0] = 0
arr1

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Booleano

In [128]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.arange(28).reshape(7, 4)

names
data

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27]])

In [127]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [129]:
# Seleccionar por máscara de valores V/F
data[names == 'Bob']

array([[ 0,  1,  2,  3],
       [12, 13, 14, 15]])

In [130]:
# Negar una expresión
data[names != 'Bob']
data[~(names == 'Bob')]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27]])

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27]])

In [134]:
data[(names=='Bob') | (names=='Will')]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

### Fancy

In [137]:
arr = np.empty((8, 4))
for i in range(8):
    arr[i] = i
    
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [138]:
# Seleccionar una lista de rows con ciertos índices
arr[[4, 5, 0, 6]]

array([[4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [139]:
arr = np.arange(32).reshape((8, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [141]:
# Lo mismo que arriba, pero con índices de columnas también
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

## Slicing

In [148]:
arr1
arr2
arr3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [166]:
# Slicing de enteros
arr[5:8]
arr[:5] # Hasta el quinto
arr[3:] # Desde el tercero

array([[12, 12, 12, 12],
       [ 7,  7,  7,  7],
       [12, 12, 12, 12]])

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [12, 12, 12, 12],
       [ 7,  7,  7,  7],
       [12, 12, 12, 12]])

In [150]:
# Se puede usar como asignación múltiple
arr[5:8] = 12
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [12, 12, 12, 12],
       [12, 12, 12, 12],
       [12, 12, 12, 12]])

In [157]:
# ¡LOS SLICES SON REFERENCIAS AL NDRRAY ORIGINAL!
arr_slice = arr1[5:8]
arr_slice[2] = 55
arr1
arr1[8] = 7
arr1

array([ 0,  1,  2,  3,  4,  5,  7, 55,  7,  9])

array([0, 1, 2, 3, 4, 5, 7, 6, 7, 9])

In [158]:
# Usa la funcion copy para obtener copias de arrays
arr_copy = arr1[5:8].copy()
arr_copy[2] = 55
arr1
arr_copy

array([0, 1, 2, 3, 4, 5, 7, 6, 7, 9])

array([ 5,  7, 55])

In [160]:
# Selecciona todo el array
arr1
arr1[:]

array([0, 1, 2, 3, 4, 5, 7, 6, 7, 9])

array([0, 1, 2, 3, 4, 5, 7, 6, 7, 9])

In [162]:
# SLICING EN N DIMENSIONES
# 2D
arr2d = np.array([[1,2,3], [4,5,6], [7,8,9]])
arr2d

In [165]:
arr2d[1:,:2]

array([[4, 5],
       [7, 8]])

In [168]:
# 3D
arr3d = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [169]:
arr3d[:2]
arr3d[:2, :1]
arr3d[:2, :1, :1]

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

array([[[1, 2, 3]],

       [[7, 8, 9]]])

array([[[1]],

       [[7]]])

# Operaciones con arrays

## Reshaping

In [187]:
# Reshape explícito
A = np.arange(8) #--> 1d array
A.reshape((2, 2, 2))
# Definicion y reshape
B = np.arange(25).reshape((5, 5))
B

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

## Matriz transpuesta y cambio de ejes

In [171]:
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [172]:
arr.T # Transpuesta

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [180]:
arr = np.arange(18).reshape((2, 3, 3))
# Cambiar ejes
arr
arr.swapaxes(1, 2)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

array([[[ 0,  3,  6],
        [ 1,  4,  7],
        [ 2,  5,  8]],

       [[ 9, 12, 15],
        [10, 13, 16],
        [11, 14, 17]]])

In [181]:
# Reordenar ejes
arr
arr.transpose((1, 0, 2))

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

array([[[ 0,  1,  2],
        [ 9, 10, 11]],

       [[ 3,  4,  5],
        [12, 13, 14]],

       [[ 6,  7,  8],
        [15, 16, 17]]])

## Productos vectoriales

In [183]:
A = [1, 2, 3]
B = [2, 3, 4]
np.dot(A, B)
np.cross(A, B)

20

array([-1,  2, -1])

# Funciones comunes

## Funciones universales (ufuncs)

In [191]:
# FUNCIONES QUE APLICAN CAMBIOS A TODOS LOS VALORES DEL ARRAY Y DEVUELVEN UN NUEVO ARRAY CON VALORES MODIFICADOS
arr = np.arange(10)

# Funcion sqrt
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [204]:
# Funcion maximum
x = np.random.randint(1, 10, (10))

y = np.random.randint(1, 10, (10))

print('X:', x)
print('Y:', y)

np.maximum(x, y)

X: [5 8 1 4 4 3 3 4 1 2]
Y: [9 2 5 9 9 8 1 1 9 8]


array([9, 8, 5, 9, 9, 8, 3, 4, 9, 8])

In [215]:
# Funcion abs
z = np.random.randint(-5, 3, (10))
z
np.abs(z)

array([ 0,  1, -1,  1, -5, -3,  2,  2, -4, -3])

array([0, 1, 1, 1, 5, 3, 2, 2, 4, 3])

## Métodos estadísticos (mean, std, etc...)

In [199]:
arr = np.random.randn(4, 3)
arr

array([[ 0.18676676, -0.75538293, -0.6115178 ],
       [-1.4066611 , -0.92323325, -1.35168461],
       [-0.97587325,  1.0536418 , -0.94939889],
       [ 2.63238206,  0.4933179 ,  0.18483612]])

In [203]:
# Promedio usando funcion integrada
arr.mean()
# Promedio usando funcion global
np.mean(arr)
# Suma
arr.sum()

-0.20190059793599455

-0.20190059793599455

-2.4228071752319345